# Generated by Django 4.2.7 on 2023-11-23 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company', models.CharField(choices=[('WSI', 'WeSupport Inc.'), ('HHI', 'Hunters Hub Inc.'), ('PSI', 'Provisor Solutions Inc.'), ('ESI', 'Ekkremis Solutions Inc.'), ('UpTC', 'Uptitude Training Corp.'), ('WGCCC', 'WeSupport Group of Company Credit Cooperative'), ('TSTC', 'Tranzend Solutions and Trading Corp.')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('code', models.CharField(default='WGC-0', max_length=15)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
