# Generated by Django 4.2.7 on 2023-11-22 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company', models.CharField(choices=[('wsi', 'WSI'), ('transcend', 'Transcend'), ('none', 'None')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('code', models.CharField(default='WGC-0', max_length=15)),
            ],
        ),
    ]
