# Generated by Django 4.2.7 on 2023-11-23 00:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0912345678', max_length=12, region='PH'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='company',
            field=models.CharField(choices=[('WSI', 'WeSupport Inc.'), ('HHI', 'Hunters Hub Inc.'), ('PSI', 'Provisor Solutions Inc.'), ('ESI', 'Ekkremis Solutions Inc.'), ('UpTC', 'Uptitude Training Corp.'), ('WGCCC', 'WeSupport Group of Company Credit Cooperative'), ('TSTC', 'Tranzend Solutions and Trading Corp.')], max_length=20),
        ),
    ]
