# Generated by Django 4.2.7 on 2023-11-23 01:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_invitation_phone_number_alter_invitation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PH'),
        ),
    ]
