# Generated by Django 4.2.7 on 2023-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_invitation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
